# Generated by Django 2.1.7 on 2019-03-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_practice', '0003_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
