# Generated by Django 2.1.7 on 2019-03-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_practice', '0004_auto_20190305_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
        migrations.AddField(
            model_name='album',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='man',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='man',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
