# Generated by Django 2.1.7 on 2019-03-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_practice', '0005_auto_20190305_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_color', models.CharField(max_length=50)),
                ('volume', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database_practice.Room')),
                ('has_furniture', models.BooleanField(default=False)),
            ],
            bases=('database_practice.room',),
        ),
    ]
